name: Build debian packages

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    # container: ${{ matrix.container }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04-arm
            rosdistro: jazzy
          - runner: ubuntu-24.04
            rosdistro: jazzy
    steps:
      - name: Create workspace
        run: |
          mkdir src

      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: "./src/onnxruntime_vendor"

      - name: Cache apt and rosdep
        id: cache-apt-rosdep
        uses: actions/cache@v4
        with:
          path: |
            /var/cache/apt/archives
            /var/lib/apt/lists
            /etc/ros/rosdep
          key: ${{ runner.os }}-apt

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main

      - name: Install TensorRT + cuDNN
        run: |
          if [ "$(uname -m)" = "x86_64" ]; then
            architecture="x86_64"
          else
            architecture="sbsa"
          fi
          echo "Architecture: $architecture"

          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/${architecture}/cuda-keyring_1.1-1_all.deb
          sudo dpkg -i cuda-keyring_1.1-1_all.deb

          sudo apt-get update
          sudo apt-get install -y libnvinfer-dev libnvinfer-plugin-dev libcudnn9-dev-cuda-12 cuda-toolkit-12-6

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ""

      - name: Run rosdep
        run: |
          rosdep update --include-eol-distros
          rosdep install -iy --from-paths src --rosdistro ${{ matrix.rosdistro }}

          sudo apt-get install -y fakeroot python3-bloom debhelper dh-python

      - name: Build
        run: |
          cd ./src/onnxruntime_vendor
          source /opt/ros/${{ matrix.rosdistro }}/setup.bash
          export DEB_BUILD_OPTIONS="parallel=$(nproc) nocheck"
          rosdep update
          bloom-generate rosdebian --ros-distro ${{ matrix.rosdistro }} .
          sed -i "s%dh_shlibdeps%dh_shlibdeps --dpkg-shlibdeps-params=--ignore-missing-info%" debian/rules
          fakeroot debian/rules binary
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}
          path: ./src/*.deb
